// Copyright (c) 2022 NetEase, Inc. All rights reserved.
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

library meeting_core;

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:collection';

import 'package:flutter/widgets.dart';
import 'package:netease_common/netease_common.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:dio/dio.dart' as http;
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:netease_meeting_kit/meeting_plugin.dart';
import 'package:netease_roomkit/netease_roomkit.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:intl/intl.dart';

export 'package:netease_common/netease_common.dart' show NEResult, VoidResult;

part 'src/meeting_core/api/api_helper.dart';
part 'src/meeting_core/api/http_api_helper.dart';
part 'src/meeting_core/config/sdk_config.dart';
part 'src/meeting_core/config/server_config.dart';
part 'src/meeting_core/device_info.dart';
part 'src/meeting_core/executor/executors.dart';
part 'src/meeting_core/executor/http_executor.dart';
part 'src/meeting_core/local/login_info_cache.dart';
part 'src/meeting_core/model/action_type.dart';
part 'src/meeting_core/model/av_state.dart';
part 'src/meeting_core/model/client_type.dart';
part 'src/meeting_core/model/impl/meeting_item_impl.dart';
part 'src/meeting_core/model/live_layout_type.dart';
part 'src/meeting_core/model/meeting_action.dart';
part 'src/meeting_core/model/meeting_chat.dart';
part 'src/meeting_core/model/meeting_item.dart';
part 'src/meeting_core/model/room_item_setting.dart';
part 'src/meeting_core/model/room_item_status.dart';
part 'src/meeting_core/model/room_item_live.dart';
part 'src/meeting_core/model/room_item_control.dart';
part 'src/meeting_core/model/member_info.dart';
part 'src/meeting_core/model/room_invitation.dart';
part 'src/meeting_core/model/meeting_interpretation.dart';
part 'src/meeting_core/model/request/create_meeting_req.dart';
part 'src/meeting_core/model/request/login_by_pwd_req.dart';
part 'src/meeting_core/model/request/js_api_permission_req.dart';
part 'src/meeting_core/model/response/anonymous_join_meeting_res.dart';
part 'src/meeting_core/model/response/account_settings.dart';
part 'src/meeting_core/remote/base_api.dart';
part 'src/meeting_core/remote/http/anonymous_join_meeting_api.dart';
part 'src/meeting_core/remote/http/cancel_meeting_api.dart';
part 'src/meeting_core/remote/http/create_meeting_api.dart';
part 'src/meeting_core/remote/http/delete_meeting_api.dart';
part 'src/meeting_core/remote/http/edit_meeting_api.dart';
part 'src/meeting_core/remote/http/get_config_api.dart';
part 'src/meeting_core/remote/http/get_contacts_info_api.dart';
part 'src/meeting_core/remote/http/get_waiting_room_properties_api.dart';
part 'src/meeting_core/remote/http/get_meeting_by_sharing_code_api.dart';
part 'src/meeting_core/remote/http/get_meeting_item_by_id_api.dart';
part 'src/meeting_core/remote/http/get_meeting_item_by_num_api.dart';
part 'src/meeting_core/remote/http/get_scheduled_members_api.dart';
part 'src/meeting_core/remote/http/get_meeting_list_by_status_api.dart';
part 'src/meeting_core/remote/http/login_by_pwd_api.dart';
part 'src/meeting_core/remote/http/schedule_meeting_api.dart';
part 'src/meeting_core/remote/http/get_settings_api.dart';
part 'src/meeting_core/remote/http/save_settings_api.dart';
part 'src/meeting_core/remote/http/room_invitation.dart';
part 'src/meeting_core/remote/http/get_web_app_list_api.dart';
part 'src/meeting_core/remote/http/get_auth_code_api.dart';
part 'src/meeting_core/remote/http/js_api_permission_api.dart';
part 'src/meeting_core/remote/http/search_contacts_api.dart';
part 'src/meeting_core/remote/http_api.dart';
part 'src/meeting_core/repository/auth_repository.dart';
part 'src/meeting_core/repository/in_meeting_repository.dart';
part 'src/meeting_core/repository/meeting_repository.dart';
part 'src/meeting_core/repository/meeting_invite_repository.dart';
part 'src/meeting_core/repository/pre_room_repository.dart';
part 'src/meeting_core/repository/service_repository.dart';
part 'src/meeting_core/repository/settings_repository.dart';
part 'src/meeting_core/repository/http_error_repository.dart';
part 'src/meeting_core/repository/web_app_repository.dart';
part 'src/meeting_core/repository/account_repository.dart';
part 'src/meeting_core/repository/core_repository.dart';
part 'src/meeting_core/repository/report_repository.dart';
part 'src/meeting_core/log/log_service.dart';
part 'src/meeting_core/model/hands_up.dart';
part 'src/meeting_core/model/whiteboard_status.dart';
part 'src/meeting_core/model/room_item_live_status.dart';
part 'src/meeting_core/model/role_type.dart';
part 'src/meeting_core/model/live_level.dart';
part 'src/meeting_core/model/live_status.dart';
part 'src/meeting_core/module_name.dart';
part 'src/meeting_core/model/request/generic_http_api_req.dart';
part 'src/meeting_core/model/room_role_configuration.dart';
part 'src/meeting_core/event_track/event_track.dart';
part 'src/meeting_core/model/contacts.dart';
part 'src/meeting_core/model/create_meeting.dart';
part 'src/meeting_core/config/debug_options.dart';
part 'src/meeting_core/model/meeting_item_live.dart';
part 'src/meeting_core/model/meeting_small_app.dart';
part 'src/meeting_core/meeting_constants.dart';
part 'src/meeting_core/model/encryption_config.dart';
part 'src/meeting_core/model/meeting_watermark.dart';
part 'src/meeting_core/model/meeting_web_app_item.dart';
part 'src/meeting_core/model/meeting_recurring_rule.dart';
part 'src/meeting_core/model/meeting_corp_info.dart';
part 'src/meeting_core/model/meeting_security_notice_info.dart';
part 'src/meeting_core/model/history_meeting_detail.dart';
part 'src/meeting_core/model/chatroom_info.dart';
part 'src/meeting_core/model/history_meeting.dart';
part 'src/meeting_core/model/feedback.dart';
part 'src/meeting_core/remote/http/get_favorite_meetings_api.dart';
part 'src/meeting_core/remote/http/add_favorite_meeting_api.dart';
part 'src/meeting_core/remote/http/get_history_meeting_detail_api.dart';
part 'src/meeting_core/remote/http/get_history_meetings_api.dart';
part 'src/meeting_core/remote/http/remove_favorite_meeting_api.dart';
part 'src/meeting_core/remote/http/get_history_meeting_api.dart';
part 'src/meeting_core/remote/http/get_security_noticeProto_api.dart';
part 'src/meeting_core/remote/http/update_avatar_api.dart';
part 'src/meeting_core/remote/http/update_nickname_api.dart';
part 'src/meeting_core/remote/http/get_app_info_api.dart';
part 'src/meeting_core/remote/http/get_sms_code_api.dart';
part 'src/meeting_core/remote/http/get_sso_account_info_api.dart';
part 'src/meeting_core/remote/http/login_by_sms_api.dart';
part 'src/meeting_core/remote/http/reset_password_api.dart';
part 'src/meeting_core/remote/http/feedback_api.dart';
part 'src/meeting_core/model/meeting_login_info.dart';
part 'src/meeting_core/model/meeting_record.dart';
part 'src/meeting_core/repository/contacts_repository.dart';
part 'src/meeting_core/repository/message_channel_repository.dart';
part 'src/meeting_core/model/session_message.dart';
part 'src/meeting_core/utils/meeting_invite_queue_util.dart';
part 'src/meeting_core/model/session_message_notify_card_data.dart';
part 'src/meeting_core/model/invite_info.dart';
part 'src/meeting_core/model/transcription.dart';
part 'src/meeting_core/model/listener/message_channel_listener.dart';
part 'src/meeting_core/utils/local_history_meeting_manager.dart';
part 'src/meeting_core/utils/in_meeting_permission_utils.dart';
part 'src/meeting_core/utils/connectivity_manager.dart';
part 'src/meeting_core/repository/meeting_context.dart';
part 'src/meeting_core/remote/http/transcription_api.dart';
part 'src/meeting_core/remote/http/check_invite_state_api.dart';
part 'src/meeting_core/remote/http/stop_member_activities_api.dart';
part 'src/meeting_core/remote/http/meeting_security_ctrl_api.dart';

/// https://office.netease.com/doc/?identity=3963dc2ced7a48259860289c5d8970af
class MeetingErrorCode {
  /// 通用失败
  static const int failed = -1;

  /// 网络错误
  static const int networkError = -4;

  /// 服务端错误码
  static const int success = 0;
  static const int paramsError = 300;
  static const int paramsNull = 301;
  static const int serverInnerError = 302;
  static const int unauthorized = 401;
  static const int forbidden = 403;
  static const int notFound = 404;
  static const int netTimeout = 408;
  static const int netError = 415;
  static const int serverError = 501;
  static const int versionNotCompatible = 513;
  static const int allocationAccountFail = 1000;
  static const int fetchAccountFail = 1001;
  static const int controlNotAllocationAccount = 1002;
  static const int phoneAlreadyRegister = 1003;
  static const int phoneNotRegister = 1004;
  static const int tokenError = 1005;
  static const int verifyError = 1006;
  static const int loginPasswordError = 1007;
  static const int passwordError = 1008;
  static const int tvAccountNotExist = 1009;
  static const int illegalPhone = 1010;
  static const int smsCodeOverLimit = 1011;
  static const int verifyInvalid = 1012;
  static const int accountNotExist = 1014;
  static const int roomLock = 1019;
  static const int roomNotExist = 2000;
  static const int roomMemberOverLimit = 2001;
  // static const int roomAlreadyExist = 2002;
  static const int nickError = 2003;
  static const int memberVideoError = 2004;
  static const int memberAudioError = 2005;
  static const int roomCidIsEmpty = 2006;
  static const int memberNotHasRoomId = 2007;
  static const int notJoinRoomCannotKick = 2008;
  static const int screenShareOverLimit = 2009;
  static const int notHostPermission = 2100;
  static const int memberNotInRoom = 2101;
  static const int controlCodeError = 2102;
  static const int audioNeedHandsUp = 2108;
  static const int allowSelfAudioOn = 2110;
  static const int audioAlreadyOn = 2111;
  static const int roomNotInProgress = 2200;
  static const int notSupport = 3003;
  static const int meetingAlreadyExists = 3100;
  static const int meetingAlreadyStarted = 3105;
  static const int meetingRecycled = 3102;
  static const int meetingNotExists = 3104;
  static const int meetingWBExists = 1006;

  /// 已有其他人共享白板
  static const int meetingNotInProgress = 1004;
}
