# Uncomment this line to define a global platform for your project
require_relative "../../meetingConfig.rb"

platform :ios, "12.0"

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.

source "https://github.com/CocoaPods/Specs.git"
# source "ssh://git@g.hz.netease.com:22222/yunxin-app/specs.git"
#source 'https://cdn.cocoapods.org/'

ENV["COCOAPODS_DISABLE_STATS"] = "true"

MeetingConfig.setup()

project "Runner", {
  "Debug" => :debug,
  "Profile" => :release,
  "Release" => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join("..", "Flutter", "Generated.xcconfig"), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join("packages", "flutter_tools", "bin", "podhelper"), flutter_root)

flutter_ios_podfile_setup

target "Runner" do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod "Marvel", "1.0.7"
  # 如果是测试阶段且是本地依赖，则根据路径引用NERoom
  if Pod.const_defined?(:MEETING_TEST) && MEETING_TEST && Pod.const_defined?(:LOCAL_DEPENDENCY) && LOCAL_DEPENDENCY
    puts "本地依赖"
    pod "NERoomKit", :path => "../../../../xkit-ios/RoomKit/NERoomKit/NERoomKit.podspec"
  end
end

target "MeetingBroadcaster" do
  use_frameworks!
  pod "NEDyldYuv"

  if Pod.const_defined?(:MEETING_TEST) && MEETING_TEST
    # 测试阶段
    if Pod.const_defined?(:LOCAL_DEPENDENCY) && LOCAL_DEPENDENCY
      # 使用本地依赖
      pod "NERoomKit", :path => "../../../../xkit-ios/RoomKit/NERoomKit/NERoomKit.podspec"
    else
      # 使用内部pod
      pod "NERoomKit-Private"
    end
  else
    # 非测试阶段
    pod "NERoomKit/ScreenShare"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["ENABLE_BITCODE"] = "NO"
      #           config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings["APPLICATION_EXTENSION_API_ONLY"] = "NO"
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= [
        "$(inherited)",
        "PERMISSION_CAMERA=1",
        "PERMISSION_MICROPHONE=1",
        "PERMISSION_CONTACTS=1",
      ]
    end
  end
end
