# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.

source 'https://github.com/CocoaPods/Specs.git'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  #   supports_swift_versions '>=4.0', '<5.0' # add
  use_frameworks!

  plugin 'cocoapods-pod-sign'
  skip_pod_bundle_sign # 用来跳过Xcode对bundle资源的签名
  # pod 'NERoomKit-Private', '1.16.0.0', :subspecs => ['Special_All']
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

 target 'MeetingBroadcaster' do
   use_frameworks!
   pod 'NEDyldYuv'
   # pod 'NERoomKit-Private/ScreenShare'
   pod 'NERoomKit/ScreenShare'
#   pod 'NEScreenShareBroadcaster', '0.5.3'
 end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#           config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            # You can remove unused permissions here
            # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
            # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)', 
              'PERMISSION_CAMERA=1',
              'PERMISSION_MICROPHONE=1'
            ]
        end
  end
end
